on:
  push:
    branches:
      - main
      - master
    pull_request:

name: Continuous Integration

jobs:
  macos:
    name: macos
    runs-on: macos-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - stable minus 6 releases
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt

      - name: check (default features)
        run: cargo check

      - name: test (default features)
        run: cargo test --no-run

      - name: clippy (default features)
        run: cargo clippy -- -D warnings

  clang-format:
    name: test clang-format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.8
      with:
        source: './objc'
        exclude: './third_party ./external'
        extensions: 'h,m'
        clangFormatVersion: 10
        style: file # read style from .clang-format

  rustfmt:
    name: test rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain with rustfmt available
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
